name: Trigger Netlify Build

on:
  push:
    branches:
      - master
    paths:
      - website/**
  schedule:
    # Every Sunday
    - cron: '0 16 * * 0'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -v -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
